name: Lurker
main: com.ne0nx3r0.lurker.Lurker
version: '0.1'
database: false
description: Lurker!
commands:
  lurk: 
    description: lurker stuff
permissions:
    lurker.lurk:
      description: Allows player to lurk